System check identified no issues (0 silenced).
November 29, 2020 - 20:00:12
Django version 3.1.3, using settings 'settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/ondrej/.local/share/virtualenvs/stream.sika.io-7EGglDH_/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/ondrej/.local/share/virtualenvs/stream.sika.io-7EGglDH_/lib/python3.9/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ondrej/Projects/www/stream.sika.io/app/views.py", line 10, in home_view
    return render(request, "home.html2")
  File "/Users/ondrej/.local/share/virtualenvs/stream.sika.io-7EGglDH_/lib/python3.9/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/ondrej/.local/share/virtualenvs/stream.sika.io-7EGglDH_/lib/python3.9/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/ondrej/.local/share/virtualenvs/stream.sika.io-7EGglDH_/lib/python3.9/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: home.html2
[29/Nov/2020 20:00:17] "GET / HTTP/1.1" 500 78028
Not Found: /favicon.ico
[29/Nov/2020 20:00:18] "GET /favicon.ico HTTP/1.1" 404 2910
